# Generated by Django 6.0.5 on 2026-06-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('FD', 'Fixed Deposit'), ('LOAN', 'Loan'), ('INS', 'Insurance')], max_length=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
